### ISSUE TITLE
use RPOPLPUSH to  Pattern:  Reliable queue

### ISSUE THREAD

**Issue by wozzup** [mjphaynes/php-resque#29]
http://redis.io/commands/rpoplpush

maybe, It's better than BLPOP?

**Comment by francislavoie** [comment]
So I was thinking about this - I totally agree this is needed, but here are my thoughts:

The way the queue is implemented currently, data loss is very unlikely as-is because workers are resilient to jobs failing, and jobs are requeued if they do fail. The likelyhood of `RPOPLPUSH` preventing data loss is very low because the failure logic is reduced to essentially power outages (including forced shutdowns of the worker processes) or bad code in the worker logic causing crashes.

On top of this, to actually recover from it, redis should be configured with AOF turned on so that every operation is written to disk and can be replayed on restart.

Some logic for the "processing" queue would need to be implemented as well for this to work correctly. I'm not exactly sure how that should be implemented, so I'd like some help on the design here.

**Comment by mjphaynes** [comment]
Closing this for now.

If someone wishes to make a pull request for this functionality (as a default or configuration item) then please feel free 🙂
