### ISSUE TITLE
Why not delete worker data in redis when stop worker?

### ISSUE THREAD

**Issue by davidtall** [mjphaynes/php-resque#60]
when I stop worker, I still see worker data like `resque:worker:iZwz9ft78ij1qqu9qd14tqZ:8417` in redis .when I restart worker ,they are still there.why not delete that when worker stopped? @francislavoie

**Comment by francislavoie** [comment]
I'm pretty sure the reason is to keep logs about what was run. If I remember correctly, those have an expiry of two weeks, so they should disappear on their own after two weeks. You can wipe them away yourself with a reset if you want. See the examples/index.php file, it has a reset action which wipes away all the data

**Comment by xelan** [comment]
Hi @davidtall! As your question has been answered, but this issue is still open after almost three months, I'll close it now. Feel free to reopen if you have any additional questions regarding this issue.
