### ISSUE TITLE
Retry & ReQueue

### ISSUE THREAD

**Issue by merlindorin** [mjphaynes/php-resque#73]
Unfortunately, I think I already know the answer but it costs nothing to ask...

Does php-resque support :
  - Requeue of failing job?
  - Retry (backoff for example) for failing job?

**Comment by xelan** [comment]
Hi @iam-merlin! Re-enqueuing will be implemented in the Resque Web UI. Automatic retry would probably also require significant adaptations in the php-resque library. There is no plan for this feature yet as far as I know.

**Comment by iam-merlin** [comment]
Thx for your quick answer as usual :D. The Web UI will be a sugar for us but I need something less user friendly and more machine friendly (something like `bin/resque job:requeue 12` and `bin/resque jobs:list:error`).

Do you have any tips to implement such commands (knowing that I'm not a redis-god)? I didn't see in code such method.

For the retry, after going deeper into the code last night, I don't feel it will be hard to implement. What I see is :
  - Add a new value "retry" in stats
  - Add a new incremental job metadata "retry"
  - Add a new config key "retry" (default value `backoff`?)
  - ReQueue on error

And ofc, all the retry logic.

Do you think my approach is silly?

**Comment by xelan** [comment]
Thank you for your quick feedback and great suggestion, @iam-merlin! Your proposed approach sounds good. It's just important to keep BC compatibility in mind, so jobs which do not have a retry value should still work without retry.

What do you mean with a default value `backoff`? That the job is retried several times with an increased time between retries? And probably the default value should be `0` (no retries) for compatibility with current applications. Otherwise, the new feature might lead to duplicate jobs instead of (expected) job failures.

**Comment by iam-merlin** [comment]
"backoff" is for the retry strategy like :
    - Incremental
    - FixedInterval
    - ExponentialBackoff.

Faut BC, I think we can keep it with default values.
