### ISSUE TITLE
Many copies of one worker process

### ISSUE THREAD

**Issue by blood73** [mjphaynes/php-resque#97]
Hello. I have 2 different workers: worker 1 and worker 2.

Worker 1 have 20 copies and it works fine. Worker 2 have 100 copies and have problems:
after several hours many copies stops with this message:

** Worker is not in list of workers or packet is corrupt, aborting
** Shutting down worker centos-8gb-nbg1-1:7527

What is that mean? How I can fix this? I use systemd process monitor

**Comment by xelan** [comment]
Hi @blood73! Thanks for reporting this issue. We already got some issues in this direction. In general, scaling of resque workers should be done via independent instances (e.g. LXC containers or docker containers) instead of one huge machine with hundreds of worker processes.

Please also check the value of `/proc/sys/kernel/pid_max` on your system. Each worker may use multiple process IDs (worker process, child process, process monitor service, job processes) which might exceed `pid_max` in case of so many worker copies.

**Comment by xelan** [comment]
Hi @blood73! Hope my suggestions helped for your use case. I'm closing this issue, feel free to reopen if you need further help.

Best regards
Andreas
